name = input("Masukan nama Anda : ")
nakut = input("Masukan nama matakuliah: ")
grup = input("Masukan grup Anda: ")
print("Haloo! "+name*2)
print("Anda tergabung dalam kelas "+nakut+" pada grup "+grup)