print("===================Cafe===================")
print("=============MASUKAN JUMLAH PESANAN=======")
capucino= int(input("CAPPUCINO       DISKON 50%      Rp 25.000       : "))
Vanila=   int(input("VANILLA LATTE   DISKON 65%      Rp 22.000       : "))
Americano=int(input("AMERICANO       DISKON 35%      Rp 30.000       : "))
Cofee =   int(input("BREWED COFFEE   DISKON 40%      Rp 20.000       : "))
print("==================TOTAL===================")
diskoncap= 25000*capucino-(25000*capucino*50/100)
diskonvan= 22000*Vanila-(22000*Vanila*65/100)
diskonam = 30000*Americano-(30000*Americano*35/100)
diskoncof= 20000*Cofee-(20000*Cofee*40/100)
jumlah = diskoncap + diskonvan + diskonam + diskoncof
print("TOTAL CAPPUCINO          : Rp",int(diskoncap))
print("TOTAL VANILLA LATTE      : Rp",int(diskonvan))
print("TOTAL AMERICANO          : Rp",int(diskonam))
print("TOTAL BREWED COFFEE      : Rp",int(diskoncof))
print("Jumlah total biaya yang harus dibayar adalah Rp", jumlah)